-- ONA — migration 002: antenatal visit schedule
--
-- One row per planned contact. The rows are generated by generateSchedule in
-- src/lib/schedule.ts from the last menstrual period, a fixed table of
-- gestational weeks (the WHO 2016 eight-contact ANC model) and the current risk
-- zone. Arithmetic and a lookup table — no model chooses a date.
--
-- Unlike assessments, visits ARE mutable: a planned visit becomes completed or
-- missed, and a schedule is regenerated when the zone changes. The immutable
-- record of what was found at a visit is the assessment it points at.

create type visit_status as enum (
  'rejalashtirilgan',    -- planned
  'bajarilgan',          -- completed
  'o''tkazib yuborilgan' -- missed
);

create table visits (
  id                      uuid primary key default gen_random_uuid(),
  pregnancy_id            uuid not null references pregnancies (id) on delete cascade,

  -- Position in the schedule, 1-based. Not a WHO contact number: the yellow
  -- zone inserts extra contacts and everything after them renumbers.
  contact_number          smallint not null,
  target_week             smallint not null,
  target_date             date not null,

  status                  visit_status not null default 'rejalashtirilgan',

  -- The assessment that completed this visit, when there is one. Nullable: a
  -- visit can be marked completed from a paper record with no assessment row.
  completed_assessment_id uuid,

  note                    text,
  created_by              uuid references auth.users (id) default auth.uid(),
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now(),

  constraint visits_contact_number_sane
    check (contact_number between 1 and 40),
  -- Wider than the WHO table on purpose: a rescheduled or catch-up contact can
  -- legitimately sit outside the standard weeks.
  constraint visits_target_week_sane
    check (target_week between 1 and 45),

  -- An assessment may only be attached to a visit that is actually completed.
  -- The reverse is allowed: completed with no assessment is a paper record.
  constraint visits_assessment_implies_completed
    check (completed_assessment_id is null or status = 'bajarilgan'),

  -- One row per contact per pregnancy.
  constraint visits_one_row_per_contact unique (pregnancy_id, contact_number),

  -- Same guarantee as escalations: the assessment that completed this visit
  -- must belong to the same pregnancy as the visit. Enforced by a composite
  -- foreign key against assessments (id, pregnancy_id) rather than trusted to
  -- the client — CHECK cannot contain the subquery this would otherwise need.
  -- completed_assessment_id is nullable and MATCH SIMPLE is the default, so the
  -- constraint simply does not apply while it is null.
  constraint visits_assessment_matches_pregnancy
    foreign key (completed_assessment_id, pregnancy_id)
    references assessments (id, pregnancy_id)
    on delete restrict
);

create index visits_pregnancy_idx on visits (pregnancy_id, target_date);
create index visits_upcoming_idx on visits (target_date)
  where status = 'rejalashtirilgan';

create trigger visits_touch before update on visits
  for each row execute function touch_updated_at();

-- ---------------------------------------------------------------------------
-- row level security
-- ---------------------------------------------------------------------------
-- Same posture as 001: authenticated staff read and write, anonymous denied.
-- DELETE is allowed here, unlike assessments — removing a superseded planned
-- contact destroys no clinical observation.

alter table visits enable row level security;

create policy visits_staff_read   on visits for select to authenticated using (true);
create policy visits_staff_insert on visits for insert to authenticated with check (true);
create policy visits_staff_update on visits for update to authenticated using (true) with check (true);
create policy visits_staff_delete on visits for delete to authenticated using (true);
